export const NATIONALITY_MAP: Record<string, string> = {
  AD: "Andorran",
  AE: "Emirati",
  AF: "Afghan",
  AG: "Antiguan",
  AI: "Anguillan",
  AL: "Albanian",
  AM: "Armenian",
  AO: "Angolan",
  AQ: "Antarctic",
  AR: "Argentinian",
  AT: "Austrian",
  AU: "Australian",
  AW: "Arubian",
  AX: "Ålandic",
  AZ: "Azerbaijani",
  BA: "Bosnian",
  BB: "Barbadian",
  BD: "Bangladeshi",
  BE: "Belgian",
  BF: "Burkinabe",
  BG: "Bulgarian",
  BH: "Bahrainian",
  BI: "Burundian",
  BJ: "Beninese",
  BL: "Barthélemois",
  BM: "Bermudan",
  BN: "Bruneian",
  BO: "Bolivian",
  BR: "Brazilian",
  BS: "Bahamian",
  BT: "Bhutanese",
  BW: "Batswana",
  BY: "Belarusian",
  BZ: "Belizean",
  CA: "Canadian",
  CC: "Cocossian",
  CD: "Congolese",
  CF: "Central African",
  CH: "Swiss",
  CI: "Ivorian",
  CK: "Cook Islander",
  CL: "Chilean",
  CM: "Cameroonian",
  CN: "Chinese",
  CO: "Colombian",
  CR: "Costa Rican",
  CU: "Cuban",
  CV: "Cape Verdean",
  CW: "Curaçaoan",
  CX: "Christmas Islander",
  CY: "Cypriot",
  CZ: "Czech",
  DE: "German",
  DJ: "Djiboutian",
  DK: "Danish",
  DO: "Dominican",
  DZ: "Algerian",
  EC: "Ecuadorean",
  EE: "Estonian",
  EG: "Egyptian",
  EH: "Sahrawi",
  ER: "Eritrean",
  ES: "Spanish",
  ET: "Ethiopian",
  FI: "Finnish",
  FJ: "Fijian",
  FK: "Falkland Islander",
  FM: "Micronesian",
  FO: "Faroese",
  FR: "French",
  GA: "Gabonese",
  GB: "British",
  GD: "Grenadian",
  GE: "Georgian",
  GF: "French Guianese",
  GH: "Ghanaian",
  GI: "Gibralterian",
  GL: "Greenlandic",
  GM: "Gambian",
  GN: "Guinean",
  GP: "Guadeloupean",
  GQ: "Equatoguinean",
  GR: "Greek",
  GT: "Guatemalan",
  GU: "Guamanian",
  GY: "Guyanese",
  HK: "Hong Konger",
  HN: "Honduran",
  HR: "Croatian",
  HT: "Haitian",
  HU: "Hungarian",
  ID: "Indonesian",
  IE: "Irish",
  IL: "Israeli",
  IM: "Manx",
  IN: "Indian",
  IQ: "Iraqi",
  IR: "Iranian",
  IS: "Icelander",
  IT: "Italian",
  JM: "Jamaican",
  JO: "Jordanian",
  JP: "Japanese",
  KE: "Kenyan",
  KG: "Kyrgyzstani",
  KH: "Cambodian",
  KI: "I-kiribati",
  KM: "Comoran",
  KN: "Kittian",
  KP: "North Korean",
  KR: "South Korean",
  KW: "Kuwaiti",
  KY: "Caymanian",
  KZ: "Kazakhstani",
  LA: "Laotian",
  LB: "Lebanese",
  LC: "Saint Lucian",
  LI: "Liechtensteiner",
  LK: "Sri Lankan",
  LR: "Liberian",
  LS: "Basotho",
  LT: "Lithunian",
  LU: "Luxembourger",
  LV: "Latvian",
  LY: "Libyan",
  MA: "Moroccan",
  MC: "Monacan",
  MD: "Moldovan",
  ME: "Montenegrin",
  MG: "Malagasy",
  MH: "Marshallese",
  MK: "Macedonian",
  ML: "Malian",
  MM: "Myanmarese",
  MN: "Mongolian",
  MO: "Macanese",
  MP: "Northern Mariana Islander",
  MQ: "Martinican",
  MR: "Mauritanian",
  MS: "Montserratian",
  MT: "Maltese",
  MU: "Mauritian",
  MV: "Maldivan",
  MW: "Malawian",
  MX: "Mexican",
  MY: "Malaysian",
  MZ: "Mozambican",
  NA: "Namibian",
  NC: "New Caledonian",
  NE: "Nigerien",
  NF: "Norfolk Islander",
  NG: "Nigerian",
  NI: "Nicaraguan",
  NL: "Dutch",
  NO: "Norwegian",
  NP: "Nepalese",
  NR: "Nauruan",
  NU: "Niuean",
  NZ: "New Zealander",
  OM: "Omani",
  PA: "Panamanian",
  PE: "Peruvian",
  PF: "French Polynesian",
  PG: "Papua New Guinean",
  PH: "Filipino",
  PK: "Pakistani",
  PL: "Polish",
  PM: "Saint-Pierrais",
  PN: "Pitcairn Islander",
  PR: "Puerto Rican",
  PS: "Palestinian",
  PT: "Portuguese",
  PW: "Palauan",
  PY: "Paraguayan",
  QA: "Qatari",
  RO: "Romanian",
  RS: "Serbian",
  RU: "Russian",
  RW: "Rwandan",
  SA: "Saudi Arabian",
  SB: "Solomon Islander",
  SC: "Seychellois",
  SD: "Sudanese",
  SE: "Swedish",
  SG: "Singaporean",
  SH: "Saint Helenian",
  SI: "Slovenian",
  SK: "Slovakian",
  SL: "Sierra Leonean",
  SM: "Sammarinese",
  SN: "Senegalese",
  SO: "Somali",
  SR: "Surinamese",
  ST: "São Tomean",
  SV: "Salvadoran",
  SY: "Syrian",
  SZ: "Swazi",
  TC: "Turks and Caicos Islander",
  TD: "Chadian",
  TG: "Togolese",
  TH: "Thai",
  TJ: "Tajikistani",
  TK: "Tokelauan",
  TL: "Timorese",
  TM: "Turkmen",
  TN: "Tunisian",
  TO: "Tongan",
  TR: "Turkish",
  TT: "Trinidadian",
  TV: "Tuvaluan",
  TW: "Taiwanese",
  TZ: "Tanzanian",
  UA: "Ukrainian",
  UG: "Ugandan",
  US: "American",
  UY: "Uruguayan",
  UZ: "Uzbekistani",
  VC: "Vincentian",
  VE: "Venezuelan",
  VG: "Virgin Islander",
  VN: "Vietnamese",
  VU: "Ni-vanuatu",
  WF: "Wallisian",
  WS: "Samoan",
  YE: "Yemeni",
  YT: "Mahoran",
  ZA: "South African",
  ZM: "Zambian",
  ZW: "Zimbabwean",
};
